//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.237
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF_EstresServicioSisFalla.WCF_SisFalla {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF_SisFalla.IServicioSISFALLA")]
    public interface IServicioSISFALLA {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSISFALLA/Guardar", ReplyAction="http://tempuri.org/IServicioSISFALLA/GuardarResponse")]
        byte[] Guardar(string token, byte[] objeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSISFALLA/GetComentariosPorNombreTabla", ReplyAction="http://tempuri.org/IServicioSISFALLA/GetComentariosPorNombreTablaResponse")]
        byte[] GetComentariosPorNombreTabla(string token, string nombreTabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSISFALLA/GetTabla", ReplyAction="http://tempuri.org/IServicioSISFALLA/GetTablaResponse")]
        byte[] GetTabla(string token, string nombreTabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSISFALLA/GetMaxSincVer", ReplyAction="http://tempuri.org/IServicioSISFALLA/GetMaxSincVerResponse")]
        byte[] GetMaxSincVer(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSISFALLA/GetRegistrosSincronizacion", ReplyAction="http://tempuri.org/IServicioSISFALLA/GetRegistrosSincronizacionResponse")]
        byte[] GetRegistrosSincronizacion(string token, string tabla, decimal versionCliente, long pkCodPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSISFALLA/Subir", ReplyAction="http://tempuri.org/IServicioSISFALLA/SubirResponse")]
        bool Subir(string token, byte[] dataSet, string modulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSISFALLA/ConfirmarSinc", ReplyAction="http://tempuri.org/IServicioSISFALLA/ConfirmarSincResponse")]
        bool ConfirmarSinc(string token, long codPersona, string nombreTabla, byte[] tabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSISFALLA/GetStrFechaHora", ReplyAction="http://tempuri.org/IServicioSISFALLA/GetStrFechaHoraResponse")]
        string GetStrFechaHora(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSISFALLA/GetTablaTest", ReplyAction="http://tempuri.org/IServicioSISFALLA/GetTablaTestResponse")]
        byte[] GetTablaTest(string token, string nombreTabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSISFALLA/IniciarSesion", ReplyAction="http://tempuri.org/IServicioSISFALLA/IniciarSesionResponse")]
        long IniciarSesion(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSISFALLA/ValidarOperacion", ReplyAction="http://tempuri.org/IServicioSISFALLA/ValidarOperacionResponse")]
        bool ValidarOperacion(long EstadoOperacion, int pk_cod_falla, long PkDCodTipoinforme, long pkcodpersona);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioSISFALLAChannel : WF_EstresServicioSisFalla.WCF_SisFalla.IServicioSISFALLA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSISFALLAClient : System.ServiceModel.ClientBase<WF_EstresServicioSisFalla.WCF_SisFalla.IServicioSISFALLA>, WF_EstresServicioSisFalla.WCF_SisFalla.IServicioSISFALLA {
        
        public ServicioSISFALLAClient() {
        }
        
        public ServicioSISFALLAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioSISFALLAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSISFALLAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSISFALLAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] Guardar(string token, byte[] objeto) {
            return base.Channel.Guardar(token, objeto);
        }
        
        public byte[] GetComentariosPorNombreTabla(string token, string nombreTabla) {
            return base.Channel.GetComentariosPorNombreTabla(token, nombreTabla);
        }
        
        public byte[] GetTabla(string token, string nombreTabla) {
            return base.Channel.GetTabla(token, nombreTabla);
        }
        
        public byte[] GetMaxSincVer(string token) {
            return base.Channel.GetMaxSincVer(token);
        }
        
        public byte[] GetRegistrosSincronizacion(string token, string tabla, decimal versionCliente, long pkCodPersona) {
            return base.Channel.GetRegistrosSincronizacion(token, tabla, versionCliente, pkCodPersona);
        }
        
        public bool Subir(string token, byte[] dataSet, string modulo) {
            return base.Channel.Subir(token, dataSet, modulo);
        }
        
        public bool ConfirmarSinc(string token, long codPersona, string nombreTabla, byte[] tabla) {
            return base.Channel.ConfirmarSinc(token, codPersona, nombreTabla, tabla);
        }
        
        public string GetStrFechaHora(string token) {
            return base.Channel.GetStrFechaHora(token);
        }
        
        public byte[] GetTablaTest(string token, string nombreTabla) {
            return base.Channel.GetTablaTest(token, nombreTabla);
        }
        
        public long IniciarSesion(string token) {
            return base.Channel.IniciarSesion(token);
        }
        
        public bool ValidarOperacion(long EstadoOperacion, int pk_cod_falla, long PkDCodTipoinforme, long pkcodpersona) {
            return base.Channel.ValidarOperacion(EstadoOperacion, pk_cod_falla, PkDCodTipoinforme, pkcodpersona);
        }
    }
}
