//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.239
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActualizadorModulosCliente.ServActualizador {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Modulo", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioActualizacion")]
    [System.SerializableAttribute()]
    public partial class Modulo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float MaxVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreModuloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float MaxVersion {
            get {
                return this.MaxVersionField;
            }
            set {
                if ((this.MaxVersionField.Equals(value) != true)) {
                    this.MaxVersionField = value;
                    this.RaisePropertyChanged("MaxVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreModulo {
            get {
                return this.NombreModuloField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreModuloField, value) != true)) {
                    this.NombreModuloField = value;
                    this.RaisePropertyChanged("NombreModulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServActualizador.IServActualizacion")]
    public interface IServActualizacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServActualizacion/GetModulos", ReplyAction="http://tempuri.org/IServActualizacion/GetModulosResponse")]
        ActualizadorModulosCliente.ServActualizador.Modulo[] GetModulos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServActualizacion/GetNombresArchivosNuevos", ReplyAction="http://tempuri.org/IServActualizacion/GetNombresArchivosNuevosResponse")]
        string[] GetNombresArchivosNuevos(ActualizadorModulosCliente.ServActualizador.Modulo modulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServActualizacion/GetArchivo", ReplyAction="http://tempuri.org/IServActualizacion/GetArchivoResponse")]
        byte[] GetArchivo(ActualizadorModulosCliente.ServActualizador.Modulo modulo, string archivo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServActualizacionChannel : ActualizadorModulosCliente.ServActualizador.IServActualizacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServActualizacionClient : System.ServiceModel.ClientBase<ActualizadorModulosCliente.ServActualizador.IServActualizacion>, ActualizadorModulosCliente.ServActualizador.IServActualizacion {
        
        public ServActualizacionClient() {
        }
        
        public ServActualizacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServActualizacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServActualizacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServActualizacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ActualizadorModulosCliente.ServActualizador.Modulo[] GetModulos() {
            return base.Channel.GetModulos();
        }
        
        public string[] GetNombresArchivosNuevos(ActualizadorModulosCliente.ServActualizador.Modulo modulo) {
            return base.Channel.GetNombresArchivosNuevos(modulo);
        }
        
        public byte[] GetArchivo(ActualizadorModulosCliente.ServActualizador.Modulo modulo, string archivo) {
            return base.Channel.GetArchivo(modulo, archivo);
        }
    }
}
