//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.239
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServicioActualizacion
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Archivo", Namespace="http://schemas.datacontract.org/2004/07/WcfServicioActualizacion")]
    public partial class Archivo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NombreField;
        
        private float VersionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IServActualizacion")]
public interface IServActualizacion
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServActualizacion/GetVersiones", ReplyAction="http://tempuri.org/IServActualizacion/GetVersionesResponse")]
    WcfServicioActualizacion.Archivo[] GetVersiones(string modulo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServActualizacion/GetArchivo", ReplyAction="http://tempuri.org/IServActualizacion/GetArchivoResponse")]
    byte[] GetArchivo(string modulo, string archivo);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServActualizacionChannel : IServActualizacion, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServActualizacionClient : System.ServiceModel.ClientBase<IServActualizacion>, IServActualizacion
{
    
    public ServActualizacionClient()
    {
    }
    
    public ServActualizacionClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServActualizacionClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServActualizacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServActualizacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public WcfServicioActualizacion.Archivo[] GetVersiones(string modulo)
    {
        return base.Channel.GetVersiones(modulo);
    }
    
    public byte[] GetArchivo(string modulo, string archivo)
    {
        return base.Channel.GetArchivo(modulo, archivo);
    }
}
