//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.296
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace repSisfalla.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("repSisfalla.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _checked {
            get {
                object obj = ResourceManager.GetObject("checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Clear {
            get {
                object obj = ResourceManager.GetObject("Clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap email_go {
            get {
                object obj = ResourceManager.GetObject("email_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap emailButton {
            get {
                object obj = ResourceManager.GetObject("emailButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Filter {
            get {
                object obj = ResourceManager.GetObject("Filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] forNotificacion {
            get {
                object obj = ResourceManager.GetObject("forNotificacion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] forNotificacion_ae {
            get {
                object obj = ResourceManager.GetObject("forNotificacion_ae", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ic_imprimir {
            get {
                object obj = ResourceManager.GetObject("ic_imprimir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap informe4 {
            get {
                object obj = ResourceManager.GetObject("informe4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InfPrelim {
            get {
                object obj = ResourceManager.GetObject("InfPrelim", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo_quantum {
            get {
                object obj = ResourceManager.GetObject("logo_quantum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pdf {
            get {
                object obj = ResourceManager.GetObject("pdf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] repAgenteContactos {
            get {
                object obj = ResourceManager.GetObject("repAgenteContactos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repCompoComprometidos {
            get {
                object obj = ResourceManager.GetObject("repCompoComprometidos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repComponenteLineas {
            get {
                object obj = ResourceManager.GetObject("repComponenteLineas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repDetalleDesconex {
            get {
                object obj = ResourceManager.GetObject("repDetalleDesconex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repDetalleEdac {
            get {
                object obj = ResourceManager.GetObject("repDetalleEdac", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repDetalleGeneralSupervisor {
            get {
                object obj = ResourceManager.GetObject("repDetalleGeneralSupervisor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repDetalleInformes {
            get {
                object obj = ResourceManager.GetObject("repDetalleInformes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repDetalleSupervisor {
            get {
                object obj = ResourceManager.GetObject("repDetalleSupervisor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repDetInterruptores {
            get {
                object obj = ResourceManager.GetObject("repDetInterruptores", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repEDACAnalisis {
            get {
                object obj = ResourceManager.GetObject("repEDACAnalisis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repEleCompometidos {
            get {
                object obj = ResourceManager.GetObject("repEleCompometidos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repFalla {
            get {
                object obj = ResourceManager.GetObject("repFalla", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repFallaAlimentadores {
            get {
                object obj = ResourceManager.GetObject("repFallaAlimentadores", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repIndicesDesconex {
            get {
                object obj = ResourceManager.GetObject("repIndicesDesconex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repNotificacion {
            get {
                object obj = ResourceManager.GetObject("repNotificacion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repOperacionDetalleEdac {
            get {
                object obj = ResourceManager.GetObject("repOperacionDetalleEdac", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repOperacionEdacCausa {
            get {
                object obj = ResourceManager.GetObject("repOperacionEdacCausa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repOperacionEdacEtapa {
            get {
                object obj = ResourceManager.GetObject("repOperacionEdacEtapa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repOperacionMesEdac {
            get {
                object obj = ResourceManager.GetObject("repOperacionMesEdac", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repRelesOperados {
            get {
                object obj = ResourceManager.GetObject("repRelesOperados", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repResumenSupervisor {
            get {
                object obj = ResourceManager.GetObject("repResumenSupervisor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repRolOpciones {
            get {
                object obj = ResourceManager.GetObject("repRolOpciones", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repUsuariopoRol {
            get {
                object obj = ResourceManager.GetObject("repUsuariopoRol", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] repUsuarioporRol {
            get {
                object obj = ResourceManager.GetObject("repUsuarioporRol", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap splash {
            get {
                object obj = ResourceManager.GetObject("splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xls {
            get {
                object obj = ResourceManager.GetObject("xls", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zoom_In_Out {
            get {
                object obj = ResourceManager.GetObject("Zoom_In_Out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
