using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Reportes;
using System.Data;
using Oracle.DataAccess.Client;

namespace repSisfalla
{
    class RptDetalleDesconex : ProveedorDatosBase
    {
        public override List<DataTable> GetDatos()
        {
            List<DataTable> resultado = new List<DataTable>();
            string strSql = string.Empty;
            string sql =
            @"SELECT DISTINCT
            F_GF_RREGFALLA_COMPONENTE.PK_COD_COMPONENTE AS CODIGO,
            TO_DATE(TO_CHAR(F_GF_RREGFALLA_COMPONENTE.FEC_APERTURA,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss') AS FECHA_APERTURA,
            F_AC_COMPONENTE.NOMBRE_COMPONENTE AS COD_COMPONENTE,
            F_AC_COMPONENTE.DESCRIPCION_COMPONENTE AS DESC_COMPONENTE,
            nvl(F_GF_RESPONSABILIDAD.TIEMPO_RESPONSABILIDAD,0) AS TIEMPO_RESPONSABILIDAD,
            nvl(F_GF_RREGFALLA_COMPONENTE.TTOTAL_DESCONEXION,0) AS TTOTAL_DESCONEXION,
            DOM_RESPO.SIGLA AS SIGLA_RESPONSABLE,
            DECODE(nvl(TIEMPO_RESPONSABILIDAD,0) + nvl(TTOTAL_DESCONEXION,0),0,DOM_PROPIE.SIGLA,nvl(DOM_RESPO.SIGLA,null)) AS RESPONSABLE,
            DOM_CAUSA.DESCRIPCION_DOMINIO AS DESC_CAUSA,
            DECODE(nvl(TIEMPO_RESPONSABILIDAD,0) + nvl(TTOTAL_DESCONEXION,0),0,DECODE(F_AC_COMPONENTE.D_TIPO_COMPONENTE,1,'AUTOMÁTICA',null),null) AS RECONEXION,
            transform_codfalla(F_GF_RREGFALLA_COMPONENTE.PK_COD_FALLA) AS NUM_FALLA,
            DOM_PROPIE.SIGLA AS SIGLA_PROPIE,
            '' AS SIGLA_TIEMPOS,
            nvl(F_GF_RREGFALLA_COMPONENTE.TIEMPO_INDISPONIBILIDAD,0) AS TIEMPO_INDISPONIBILIDAD,
            nvl(F_GF_RREGFALLA_COMPONENTE.TIEMPO_PRECONEXION,0) AS TIEMPO_PRECONEXION,
            nvl(F_GF_RREGFALLA_COMPONENTE.TIEMPO_CONEXION,0) AS TIEMPO_CONEXION,
            nvl(F_GF_RREGFALLA_COMPONENTE.TIEMPO_SISTEMA,0) AS TIEMPO_SISTEMA,
            nvl(F_GF_RREGFALLA_COMPONENTE.TIEMPO_P_SIST,0) AS TIEMPO_PSISTEMA,
            nvl(F_GF_RREGFALLA_COMPONENTE.TIEMPO_P_OPER,0) AS TIEMPO_POPERACION,
            DECODE(F_AC_COMPONENTE.D_TIPO_COMPONENTE,1,'LINEAS',9,'AUTOTRANFORMADORES') AS TIPO_COMPONENTE,
            DECODE(F_GF_RREGFALLA_COMPONENTE.PK_D_COD_TIPOINFORME,20,'PRELIMINAR',21,'FINAL',22,'FINAL') AS TIPO_INFORME

            FROM
            F_GF_RREGFALLA_COMPONENTE
            LEFT JOIN F_GF_RESPONSABILIDAD ON F_GF_RREGFALLA_COMPONENTE.PK_COD_FALLA = F_GF_RESPONSABILIDAD.PK_COD_FALLA AND F_GF_RREGFALLA_COMPONENTE.PK_ORIGEN_INFORME = F_GF_RESPONSABILIDAD.PK_ORIGEN_INFORME AND F_GF_RREGFALLA_COMPONENTE.PK_D_COD_TIPOINFORME = F_GF_RESPONSABILIDAD.PK_D_COD_TIPOINFORME AND F_GF_RREGFALLA_COMPONENTE.PK_COD_COMPONENTE = F_GF_RESPONSABILIDAD.PK_COD_COMPONENTE AND F_GF_RREGFALLA_COMPONENTE.FEC_APERTURA = F_GF_RESPONSABILIDAD.FEC_APERTURA
            LEFT JOIN F_AC_COMPONENTE ON F_GF_RREGFALLA_COMPONENTE.PK_COD_COMPONENTE = F_AC_COMPONENTE.PK_COD_COMPONENTE
            LEFT JOIN F_AP_PERSONA DOM_RESPO ON F_GF_RESPONSABILIDAD.PK_COD_PERSONA_RESPONSABLE = DOM_RESPO.PK_COD_PERSONA
            LEFT JOIN F_GF_INFORMEFALLA ON F_GF_RREGFALLA_COMPONENTE.PK_COD_FALLA = F_GF_INFORMEFALLA.PK_COD_FALLA AND F_GF_RREGFALLA_COMPONENTE.PK_ORIGEN_INFORME = F_GF_INFORMEFALLA.PK_ORIGEN_INFORME AND F_GF_RREGFALLA_COMPONENTE.PK_D_COD_TIPOINFORME = F_GF_INFORMEFALLA.PK_D_COD_TIPOINFORME
            LEFT JOIN P_DEF_DOMINIOS DOM_CAUSA ON F_GF_INFORMEFALLA.D_COD_CAUSA = DOM_CAUSA.COD_DOMINIO
            LEFT JOIN F_AP_PERSONA DOM_PROPIE ON F_AC_COMPONENTE.PROPIETARIO = DOM_PROPIE.PK_COD_PERSONA

            WHERE
            F_AC_COMPONENTE.D_TIPO_COMPONENTE IN (1, 9) AND
            F_AC_COMPONENTE.PROPIETARIO IN (6, 20, 21, 28, 29, 11) AND
            F_GF_RREGFALLA_COMPONENTE.PK_ORIGEN_INFORME = 7 
            AND 
            (
            F_GF_RREGFALLA_COMPONENTE.PK_D_COD_TIPOINFORME = 20  
            OR (F_GF_RREGFALLA_COMPONENTE.PK_COD_FALLA, F_GF_RREGFALLA_COMPONENTE.PK_D_COD_TIPOINFORME) IN 
                        (
                        SELECT R.PK_COD_FALLA, R.ULTIMO_ESTADO AS PK_D_COD_TIPOINFORME from v_gf_rregfalla_ultimoestado R
                        WHERE
                        R.ultimo_estado in (21,22)
                        )
            )
            ORDER BY
            1 ASC,
            11 ASC";

            strSql = 
            @"select 
            DISTINCT A.*, 'DENTRO STI' AS CAMPO1 FROM
            (
            {0}
            ) A, F_AC_COMPONENTE_STI B
            WHERE
            A.CODIGO in (SELECT F_AC_COMPONENTE_STI.PK_COD_COMPONENTE FROM F_AC_COMPONENTE_STI WHERE F_AC_COMPONENTE_STI.FECHA_FIN IS null)

            UNION
            select DISTINCT A.*, 'FUERA STI' AS CAMPO1 FROM
            (
            {0}
            ) A, F_AC_COMPONENTE_STI B
            WHERE
             A.CODIGO not in (SELECT F_AC_COMPONENTE_STI.PK_COD_COMPONENTE FROM F_AC_COMPONENTE_STI WHERE F_AC_COMPONENTE_STI.FECHA_FIN IS null)
            ";

            strSql = string.Format(strSql, sql);

            OracleCommand cmd = CrearComando(strSql);
            DataTable tablaDetalleDominio = EjecutarComando(cmd, "DetalleDesconex");
            resultado.Add(tablaDetalleDominio);

            return resultado;
        }

        public override TipoPanel GetTipoPanel()
        {
            return TipoPanel.Parametros;
        }

        public override System.Resources.ResourceManager GetResourceManager()
        {
            return Properties.Resources.ResourceManager;
        }
    }
}
